MangoAutomation/ma-dashboards

Custom Dashboards/web/mdAdmin/views/examples/adaptiveLayouts.html, Custom Dashboards/web/templates/adaptiveLayouts/fiveCardA.html, Custom Dashboards/web/templates/adaptiveLayouts/fiveCardB.html, Custom Dashboards/web/templates/adaptiveLayouts/fiveCardC.html, Custom Dashboards/web/templates/adaptiveLayouts/fiveCardD.html, Custom Dashboards/web/templates/adaptiveLayouts/fourCardA.html, Custom Dashboards/web/templates/adaptiveLayouts/fourCardB.html, Custom Dashboards/web/templates/adaptiveLayouts/fourCardC.html, Custom Dashboards/web/templates/adaptiveLayouts/fourSquare.html, Custom Dashboards/web/templates/adaptiveLayouts/fourTop.html, Custom Dashboards/web/templates/adaptiveLayouts/nineSquare.html, Custom Dashboards/web/templates/adaptiveLayouts/threeCardA.html, Custom Dashboards/web/templates/adaptiveLayouts/threeCardB.html
Dynamically linked source code to code editor, fixed thumbnails layout
=> Updated Adaptive Layouts Example Page

UI/classes/i18n.properties, UI/web-src/ngMango/components/mailingLists/mailingList.css, UI/web-src/ngMango/components/mailingLists/mailingList.html, UI/web-src/ngMango/components/mailingLists/mailingList.js, UI/web-src/ngMango/components/mailingLists/mailingListList.html, UI/web-src/ngMango/components/mailingLists/mailingListList.js, UI/web-src/ngMango/components/mailingLists/mailingListSelect.html, UI/web-src/ngMango/components/mailingLists/mailingListSelect.js, UI/web-src/ngMango/components/mailingLists/mailingListSetup.html, UI/web-src/ngMango/components/mailingLists/mailingListSetup.js, UI/web-src/ngMango/services/mailingList.js, UI/web-src/ui/menuItems.js
Mailing list angular UI finished
=> Mailing List

UI/web-src/ngMango/components/scriptingEditor/scriptingEditor.html, UI/web-src/ngMango/components/scriptingEditor/scriptingEditor.js
- The translation was already in ma-dashboards translation file.
- The close button was moved at the bottom of validate button.
- When closing the output the line is removed.
=> scripting editor fixes

UI/classes/i18n.properties, UI/web-src/ngMango/components/serialPortsSelect/serialPortSelect.html, UI/web-src/ngMango/components/serialPortsSelect/serialPortSelect.js, UI/web-src/ngMango/ngMango.js, UI/web-src/ngMango/ngMangoServices.js, UI/web-src/ngMango/services/serialPort.js
- You can select one or multiple serial ports.
- You can show/hide Icon
- You can customize label
- You can add clear option
=> Serial port select component

UI/classes/i18n.properties, UI/web-src/ngMango/components/serialPortsSelect/serialPortSelect.html, UI/web-src/ngMango/components/serialPortsSelect/serialPortSelect.js, UI/web-src/ngMango/services/serialPort.js
- Added an refresh icon button with tooltip after the select input.
- The list only get updated with `refresh=true` when click the refresh button.
- A Dialog message is shown after the list is refreshed.
=> add refresh button

UI/web-src/ngMango/components/eventHandlerEditor/eventHandlerEmailEditor.html, UI/web-src/ngMango/components/eventHandlerEditor/eventHandlerSetPointEditor.html
Will need to look everywhere the scripting editor is used.
=> Bug fix: Scripting permissions not sent

UI/web-src/ngMango/components/scriptContext/scriptContext.html
add tags column to script context table so it is easier to find data points
=> add tags column to script context table

UI/web-src/ui/systemStatus/loggingConsole.html
I feel this makes it a lot easier to find the log file
=> Order loggging files by date

UI/classes/i18n.properties, UI/web-src/ngMango/components/virtualSerialPort/virtualSerialPortSetup.html, UI/web-src/ngMango/services/virtualSerialPort.js
solve https://github.com/infiniteautomation/ma-dashboards/issues/261
=> add remote IP whitelist input

UI/web-src/ngMango/directives/watchListChart.js
I really like the manual scroll and zoom. would be great to be able to add it to the watchlist charts.
=> Add options to extend watch list chart.

UI/classes/i18n.properties, UI/web-src/ngMango/components/eventDetectorEditor/eventDetectorEditor.html
=> Succesfully added event detector permision inputs

UI/web-src/ngMango/directives/setPointValue.js, UI/web-src/ngMango/services/setPointDialog.html
Potencial fix infiniteautomation/ma-modules-public#63
=> Potencial fix for dialog not closing on point value set.

UI/classes/i18n.properties, UI/web-src/ngMango/components/logFileView/logFileView.html, UI/web-src/ngMango/components/logFileView/logFileView.js, UI/web-src/ngMango/components/scriptingEditor/scriptingEditor.html, UI/web-src/ngMango/ngMango.js, UI/web-src/ngMango/ngMangoServices.js, UI/web-src/ngMango/services/logFileView.js
Succesfully added and implementing new log redirect component across mentioned components infiniteautomation/ma-core-public#1545
=> Issue 1545

UI/web-src/ui/views/help/emailEventHandler.html, UI/web-src/ui/views/help/processEventHandler.html
Completed for infiniteautomation/ma-core-public#1561 
- email event handler
- Process event handler
=> Updated help docs with mango javascript redirect

UI/web-src/ngMango/components/dataSourceEditor/dataSourceEditor.html
=> Added read permison dropdown

UI/web-src/ngMango/components/eventHandlerEditor/eventHandlerSetPointEditor.html
=> Updated set point value validate URL

UI/classes/i18n.properties, UI/classes/i18n_es.properties, UI/web-src/ui/components/dataSourcePage/dataSourcePage.html
infiniteautomation/ma-modules-public#88
=> Added datasource export tools

UI/web-src/ui/components/dataSourcePage/dataSourcePage.html
infiniteautomation/ma-modules-public#88
=> Added new export url for datapoints

UI/web-src/ui/components/systemSettingsPage/systemSettingsPage.html, UI/web-src/ui/components/systemSettingsPage/systemSettingsPage.js
Implemented ng-change for the dropdown
=> System settings md resolution fix

UI/RELEASE-NOTES, UI/web-src/ngMango/components/userEditor/userEditor.html, UI/web-src/ngMango/components/userEditor/userEditor.js
=> Fixed issue when non admin users couldn't create new users due to permissions input not appearing

UI/RELEASE-NOTES, UI/web-src/ui/components/watchListBuilder/watchListBuilder.js
=> Watch list builder - Selected Points not showing more them 20 points.

UI/RELEASE-NOTES, UI/resources/i18n.properties, UI/resources/i18n_es.properties, UI/web-src/ngMango/components/userTable/userTable.html
=> Show user count in users page

UI/web-src/ngMango/components/publisherEditor/publisherEditor.html, UI/web-src/ngMango/components/publisherEditor/publisherEditor.js, UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.html, UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.js, UI/web-src/ngMango/components/publisherPointsTab/publisherPointsTab.html, UI/web-src/ngMango/components/publisherPointsTab/publisherPointsTab.js, UI/web-src/ngMango/components/publisherPointsTable/publisherPointsTable.js, UI/web-src/ui/components/publisherPage/publisherPage.js
This pr fixes #RAD-1585 and #RAD-1584
=> Publisher point fixes

UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.css, UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.html, UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.js, UI/web-src/ngMango/components/publisherPointsTab/publisherPointsTab.js
=> Fixed error handeling

UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.js
Fixed error handeling on larger data sets with individual removal
=> Fixed error handeling on larger sets

UI/RELEASE-NOTES, UI/resources/i18n.properties, UI/web-src/ngMango/components/dataPointSelector/dataPointSelector.css, UI/web-src/ngMango/components/dataPointSelector/dataPointSelector.html, UI/web-src/ui/menuItems.js, UI/web-src/ui/views/help/dataPointSelector.html
=> Data point selector Help

.github/workflows/dependabot.yml
=> RAD-2546-Create dependabot.yml

UI/web-src/ngMango/piMango.css, UI/web-src/ui/uiSettings.json
=> PI-1939, PI-1940 - fix ui discrepancies on admin home and data sources page

UI/RELEASE-NOTES, UI/web-src/ngMango/components/publisherPointsCreator/publisherPointsCreator.js
Backported changes for https://github.com/RadixIoT/mango/pull/97
=> RAD-3824 Add missing validations for published points

UI/RELEASE-NOTES, UI/resources/i18n.properties, UI/web-src/ngMango/services/dialogHelper.js, UI/web-src/ngMango/services/systemActions.js
Backported changes for https://github.com/RadixIoT/mango/pull/143
=> NoSql module updates (#143)

UI/RELEASE-NOTES, UI/yarn.lock
https://radixiot.atlassian.net/browse/RAD-2888
https://radixiot.atlassian.net/browse/RAD-3962
https://github.com/RadixIoT/mango/blob/main/UI/yarn.lock#L4834
command use to upgrade library
`yarn upgrade jszip`
=> RAD-3962 Update jszip to v3.10.1

UI/RELEASE-NOTES, UI/web-src/ngMango/components/publisherPointsTab/publisherPointsTab.html
Backported changes for https://github.com/RadixIoT/mango/pull/237
=> RAD-3969 Exclude published points table 4.5.x

UI/RELEASE-NOTES, UI/resources/i18n.properties, UI/web-src/ngMango/directives/eventsTable.html, UI/web-src/ngMango/directives/eventsTable.js, UI/web-src/ui/menuItems.js, UI/web-src/ui/systemSettings/eventsExport.html, UI/web-src/ui/views/help/eventsExport.html
Backported changes for https://github.com/RadixIoT/mango/pull/296
=> Mango Event export modifications 4.5.x
